# Generated by Django 5.2.5 on 2026-08-04 17:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstagramAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ig_business_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("ig_username", models.CharField(blank=True, max_length=150)),
                ("ig_name", models.CharField(blank=True, max_length=150)),
                ("profile_picture_url", models.URLField(blank=True)),
                ("followers_count", models.PositiveIntegerField(default=0)),
                ("media_count", models.PositiveIntegerField(default=0)),
                ("facebook_page_id", models.CharField(max_length=64)),
                ("facebook_page_name", models.CharField(blank=True, max_length=150)),
                ("encrypted_access_token", models.TextField()),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("reconnect_required", "Reconnect Required"),
                            ("disconnected", "Disconnected"),
                        ],
                        default="connected",
                        max_length=25,
                    ),
                ),
                ("webhook_subscribed", models.BooleanField(default=False)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instagram_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "instagram_accounts",
            },
        ),
        migrations.CreateModel(
            name="InstagramComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("media_id", models.CharField(max_length=64)),
                ("comment_id", models.CharField(max_length=64, unique=True)),
                ("from_user_id", models.CharField(max_length=64)),
                ("from_username", models.CharField(blank=True, max_length=150)),
                ("text", models.TextField(blank=True)),
                ("replied", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="instagram.instagramaccount",
                    ),
                ),
            ],
            options={
                "db_table": "instagram_comments",
            },
        ),
        migrations.CreateModel(
            name="InstagramEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("story_mention", "Story Mention"),
                            ("story_reply", "Story Reply"),
                            ("follow", "Follow"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("sender_id", models.CharField(blank=True, max_length=64)),
                ("payload", models.JSONField(default=dict)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="instagram.instagramaccount",
                    ),
                ),
            ],
            options={
                "db_table": "instagram_events",
            },
        ),
        migrations.CreateModel(
            name="InstagramMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ig_message_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("sender_id", models.CharField(db_index=True, max_length=64)),
                ("recipient_id", models.CharField(max_length=64)),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=10,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("file", "File"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("media_url", models.URLField(blank=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="instagram.instagramaccount",
                    ),
                ),
            ],
            options={
                "db_table": "instagram_messages",
            },
        ),
        migrations.CreateModel(
            name="InstagramWebhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(db_index=True, max_length=50)),
                ("payload", models.JSONField()),
                ("signature_valid", models.BooleanField(default=False)),
                ("processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="instagram.instagramaccount",
                    ),
                ),
            ],
            options={
                "db_table": "instagram_webhooks",
            },
        ),
        migrations.AddIndex(
            model_name="instagramaccount",
            index=models.Index(
                fields=["user", "status"], name="instagram_a_user_id_b0728f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instagramcomment",
            index=models.Index(
                fields=["account", "-created_at"], name="instagram_c_account_789e84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instagramevent",
            index=models.Index(
                fields=["account", "event_type", "-created_at"],
                name="instagram_e_account_d19f30_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="instagrammessage",
            index=models.Index(
                fields=["account", "sender_id", "-created_at"],
                name="instagram_m_account_ce0e7e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="instagrammessage",
            index=models.Index(
                fields=["account", "direction", "created_at"],
                name="instagram_m_account_d377aa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="instagramwebhook",
            index=models.Index(
                fields=["event_type", "processed"],
                name="instagram_w_event_t_188770_idx",
            ),
        ),
    ]
